title: My Blog
description: I am a cyber security engineering student and a penetration tester,  Welcome to my blog where I will be publishing writeups of machines and challenges from HackTheBox and sharing with you some of my personal projects
remote_theme: pages-themes/hacker@v0.2.0
